const PREFIX_MAP: [string, string][] = [
  ["EA", "es"], ["EB", "es"], ["EC", "es"], ["ED", "es"], ["EE", "es"], ["EF", "es"], ["EG", "es"], ["EH", "es"],
  ["AM", "es"], ["AN", "es"], ["AO", "es"],
  ["K", "us"], ["N", "us"], ["W", "us"],
  ["AA", "us"], ["AB", "us"], ["AC", "us"], ["AD", "us"], ["AE", "us"], ["AF", "us"], ["AG", "us"], ["AH", "us"], ["AI", "us"], ["AJ", "us"], ["AK", "us"], ["AL", "us"],
  ["KA", "us"], ["KB", "us"], ["KC", "us"], ["KD", "us"], ["KE", "us"], ["KF", "us"], ["KG", "us"], ["KH", "us"], ["KI", "us"], ["KJ", "us"], ["KK", "us"], ["KL", "us"], ["KM", "us"], ["KN", "us"], ["KO", "us"], ["KP", "us"], ["KQ", "us"], ["KR", "us"], ["KS", "us"], ["KT", "us"], ["KU", "us"], ["KV", "us"], ["KW", "us"], ["KX", "us"], ["KY", "us"], ["KZ", "us"],
  ["NA", "us"], ["NB", "us"], ["NC", "us"], ["ND", "us"], ["NE", "us"], ["NF", "us"], ["NG", "us"], ["NH", "us"], ["NI", "us"], ["NJ", "us"], ["NK", "us"], ["NL", "us"], ["NM", "us"], ["NN", "us"], ["NO", "us"], ["NP", "us"], ["NQ", "us"], ["NR", "us"], ["NS", "us"], ["NT", "us"], ["NU", "us"], ["NV", "us"], ["NW", "us"], ["NX", "us"], ["NY", "us"], ["NZ", "us"],
  ["WA", "us"], ["WB", "us"], ["WC", "us"], ["WD", "us"], ["WE", "us"], ["WF", "us"], ["WG", "us"], ["WH", "us"], ["WI", "us"], ["WJ", "us"], ["WK", "us"], ["WL", "us"], ["WM", "us"], ["WN", "us"], ["WO", "us"], ["WP", "us"], ["WQ", "us"], ["WR", "us"], ["WS", "us"], ["WT", "us"], ["WU", "us"], ["WV", "us"], ["WW", "us"], ["WX", "us"], ["WY", "us"], ["WZ", "us"],
  ["VE", "ca"], ["VA", "ca"], ["VB", "ca"], ["VC", "ca"], ["VD", "ca"], ["VO", "ca"], ["VX", "ca"], ["VY", "ca"],
  ["CF", "ca"], ["CG", "ca"], ["CH", "ca"], ["CI", "ca"], ["CJ", "ca"], ["CK", "ca"], ["CY", "ca"], ["CZ", "ca"],
  ["G", "gb"], ["M", "gb"],
  ["GA", "gb"], ["GB", "gb"], ["GC", "gb"], ["GD", "gb"], ["GE", "gb"], ["GF", "gb"], ["GG", "gb"], ["GH", "gb"], ["GI", "gb"], ["GJ", "gb"], ["GK", "gb"], ["GL", "gb"], ["GM", "gb"], ["GN", "gb"], ["GO", "gb"], ["GP", "gb"], ["GQ", "gb"], ["GR", "gb"], ["GS", "gb"], ["GT", "gb"], ["GU", "gb"], ["GV", "gb"], ["GW", "gb"], ["GX", "gb"], ["GZ", "gb"],
  ["MA", "gb"], ["MB", "gb"], ["MC", "gb"], ["MD", "gb"], ["ME", "gb"], ["MF", "gb"], ["MG", "gb"], ["MH", "gb"], ["MI", "gb"], ["MJ", "gb"], ["MK", "gb"], ["ML", "gb"], ["MM", "gb"], ["MN", "gb"], ["MO", "gb"], ["MP", "gb"], ["MQ", "gb"], ["MR", "gb"], ["MS", "gb"], ["MT", "gb"], ["MU", "gb"], ["MV", "gb"], ["MW", "gb"], ["MX", "gb"], ["MY", "gb"], ["MZ", "gb"],
  ["2E", "gb"], ["2D", "gb"], ["2I", "gb"], ["2M", "gb"], ["2W", "gb"],
  ["F", "fr"],
  ["FA", "fr"], ["FB", "fr"], ["FC", "fr"], ["FD", "fr"], ["FE", "fr"], ["FF", "fr"], ["FG", "fr"], ["FH", "fr"], ["FI", "fr"], ["FJ", "fr"], ["FK", "fr"], ["FL", "fr"], ["FM", "fr"], ["FN", "fr"], ["FO", "fr"], ["FP", "fr"], ["FQ", "fr"], ["FR", "fr"], ["FS", "fr"], ["FT", "fr"], ["FU", "fr"], ["FV", "fr"], ["FW", "fr"], ["FX", "fr"], ["FY", "fr"],
  ["DL", "de"], ["DA", "de"], ["DB", "de"], ["DC", "de"], ["DD", "de"], ["DE", "de"], ["DF", "de"], ["DG", "de"], ["DH", "de"], ["DI", "de"], ["DJ", "de"], ["DK", "de"], ["DM", "de"], ["DN", "de"], ["DO", "de"], ["DP", "de"], ["DQ", "de"], ["DR", "de"],
  ["I", "it"],
  ["IA", "it"], ["IB", "it"], ["IC", "it"], ["ID", "it"], ["IE", "it"], ["IF", "it"], ["IG", "it"], ["IH", "it"], ["II", "it"], ["IJ", "it"], ["IK", "it"], ["IL", "it"], ["IM", "it"], ["IN", "it"], ["IO", "it"], ["IP", "it"], ["IQ", "it"], ["IR", "it"], ["IS", "it"], ["IT", "it"], ["IU", "it"], ["IV", "it"], ["IW", "it"], ["IX", "it"], ["IY", "it"], ["IZ", "it"],
  ["PA", "nl"], ["PB", "nl"], ["PC", "nl"], ["PD", "nl"], ["PE", "nl"], ["PF", "nl"], ["PG", "nl"], ["PH", "nl"], ["PI", "nl"],
  ["ON", "be"],
  ["HB", "ch"], ["HB9", "ch"],
  ["OE", "at"],
  ["CT", "pt"],
  ["SV", "gr"],
  ["OH", "fi"],
  ["SM", "se"], ["SA", "se"], ["SB", "se"], ["SC", "se"], ["SD", "se"], ["SE", "se"], ["SF", "se"], ["SG", "se"], ["SH", "se"], ["SI", "se"], ["SJ", "se"], ["SK", "se"], ["SL", "se"],
  ["LA", "no"], ["LB", "no"], ["LC", "no"], ["LD", "no"], ["LE", "no"], ["LF", "no"], ["LG", "no"], ["LH", "no"], ["LI", "no"], ["LJ", "no"], ["LK", "no"], ["LL", "no"], ["LM", "no"], ["LN", "no"],
  ["OZ", "dk"],
  ["EI", "ie"],
  ["SP", "pl"], ["SQ", "pl"], ["SR", "pl"], ["SO", "pl"], ["SN", "pl"],
  ["OK", "cz"], ["OL", "cz"],
  ["OM", "sk"],
  ["HA", "hu"], ["HG", "hu"],
  ["YO", "ro"], ["YP", "ro"], ["YQ", "ro"], ["YR", "ro"],
  ["LZ", "bg"],
  ["YU", "rs"],
  ["9A", "hr"],
  ["S5", "si"],
  ["Z3", "mk"],
  ["ZA", "al"],
  ["YT", "rs"], ["YZ", "rs"],
  ["UR", "ua"], ["US", "ua"], ["UT", "ua"], ["UU", "ua"], ["UV", "ua"], ["UW", "ua"], ["UX", "ua"], ["UY", "ua"], ["UZ", "ua"],
  ["UA", "ru"], ["UB", "ru"], ["UC", "ru"], ["UD", "ru"], ["UE", "ru"], ["UF", "ru"], ["UG", "ru"], ["UH", "ru"], ["UI", "ru"],
  ["JA", "jp"], ["JB", "jp"], ["JC", "jp"], ["JD", "jp"], ["JE", "jp"], ["JF", "jp"], ["JG", "jp"], ["JH", "jp"], ["JI", "jp"], ["JJ", "jp"], ["JK", "jp"], ["JL", "jp"], ["JM", "jp"], ["JN", "jp"], ["JO", "jp"], ["JP", "jp"], ["JQ", "jp"], ["JR", "jp"], ["JS", "jp"],
  ["HL", "kr"],
  ["BV", "tw"], ["BW", "tw"], ["BX", "tw"],
  ["BY", "cn"], ["BZ", "cn"],
  ["VU", "in"],
  ["AP", "pk"],
  ["A4", "om"], ["A41", "om"], ["A42", "om"], ["A43", "om"], ["A44", "om"], ["A45", "om"], ["A46", "om"], ["A47", "om"],
  ["A6", "ae"],
  ["A7", "qa"],
  ["A9", "bh"],
  ["9K", "kw"],
  ["HZ", "sa"],
  ["OD", "lb"],
  ["4X", "il"], ["4Z", "il"],
  ["TA", "tr"], ["TB", "tr"], ["TC", "tr"],
  ["SU", "eg"],
  ["CN", "ma"],
  ["7X", "dz"],
  ["3V", "tn"],
  ["5A", "ly"],
  ["ST", "sd"],
  ["5N", "ng"],
  ["5Z", "ke"],
  ["ZS", "za"], ["ZR", "za"], ["ZT", "za"], ["ZU", "za"],
  ["VK", "au"],
  ["ZL", "nz"],
  ["PY", "br"], ["PP", "br"], ["PQ", "br"], ["PR", "br"], ["PS", "br"], ["PT", "br"], ["PU", "br"], ["PV", "br"], ["PW", "br"], ["PX", "br"],
  ["LU", "ar"], ["LO", "ar"], ["LP", "ar"], ["LQ", "ar"], ["LR", "ar"], ["LS", "ar"], ["LT", "ar"], ["LV", "ar"], ["LW", "ar"],
  ["CE", "cl"],
  ["HC", "ec"],
  ["OA", "pe"],
  ["CP", "bo"],
  ["CX", "uy"],
  ["YV", "ve"],
  ["HK", "co"],
  ["TI", "cr"],
  ["HP", "pa"],
  ["XE", "mx"], ["XA", "mx"], ["XB", "mx"], ["XC", "mx"], ["XD", "mx"], ["XF", "mx"],
  ["CO", "cu"],
  ["HI", "do"],
  ["HR", "hn"],
  ["TG", "gt"],
  ["YS", "sv"],
];

PREFIX_MAP.sort((a, b) => b[0].length - a[0].length);

export function getCountryCode(callsign: string): string | null {
  if (!callsign) return null;
  const upper = callsign.toUpperCase();
  for (const [prefix, cc] of PREFIX_MAP) {
    if (upper.startsWith(prefix)) {
      return cc;
    }
  }
  return null;
}

export function getFlagUrl(countryCode: string): string {
  return `https://flagcdn.com/w40/${countryCode}.png`;
}
